## 2.4.1 넘파이

### 넘파이 배열

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
a = np.array([[1,2,3], [1,5,9], [3,5,7]])

print(a.ndim) # 배열의 차원 수 : 2차원 배열

print(a.shape) # 배열의 형태 : 3x3 

print(a.size) # 원소의 총 개수

print(a.dtype) # 원소의 자료형

2
(3, 3)
9
int64


In [15]:
a = np.zeros((2, 3)) #원소가 모두 0인 배열 생성
print(a)      

b = np.ones((2,1)) #원소가 모두 1인 배열 생성
print(b) 

c = np.empty((2,2)) #원소값을 초기화하지 않은 배열 생성 - 매우 크거나 작은 값이 들어감
print(c)

d = np.arange(10, 30, 5) # 10부터 30전 까지 5단위로 배열 생성 (파이썬의 range랑 비슷)
print(d)

e = np.full((2, 2), 4) #원소가 모두 4인 배열 생성
print(e)      

f = np.eye(3) # 3x3 크기의 단위행렬!!! 생성
print(f)     

g = np.random.random((2, 2)) # 임의값을 가지는 배열 생성
print(g) 

[[0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]]
[[2.e-323 2.e-323]
 [2.e-323 2.e-323]]
[10 15 20 25]
[[4 4]
 [4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.11413358 0.33293966]
 [0.80929908 0.89920558]]


### 넘파이 기본연산

In [18]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a+b)
print(np.add(a, b))

print(b-a)
print(np.subtract(b, a))

print(a**2)

print(b < 15)


C = np.array([[1, 2],
              [3, 4]])
D = np.array([[10, 20],
              [30, 10]])

print(C*D) # 원소별 곱셈

print(np.dot(C, D)) # 내적
print(C.dot(D)) # 내적


[11 22 33]
[11 22 33]
[ 9 18 27]
[ 9 18 27]
[1 4 9]
[ True False False]
[[10 40]
 [90 40]]
[[ 70  40]
 [150 100]]
[[ 70  40]
 [150 100]]


In [19]:
a = np.array([[ 1, 2, 3, 4],
              [ 5, 6, 7, 8],
              [ 1, 3, 5, 7]])

print(a.sum(axis=0)) # 0축, 즉 열을 기준으로한 덧셈

print(a.sum(axis=1)) # 1축, 즉 행을 기준으로한 덧셈

print(a.max(axis=1)) # 각 행에서의 최대값

[ 7 11 15 19]
[10 26 16]
[4 8 7]


### 넘파이 배열 인덱싱, 슬라이싱

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[3])

print(a[-1])

print(a[2:5])

print(a[2:])
print(a[:4])

4
7
[3 4 5]
[3 4 5 6 7]
[1 2 3 4]


In [21]:
a = np.array([[ 1, 2, 3],
              [ 4, 5, 6],
              [ 7, 8, 9]])

print(a[1, 2])
print(a[:, 1])

print(a[-1])

6
[2 5 8]
[7 8 9]


### 넘파이 배열 형태 변환

In [26]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])

print(a.ravel()) # == flatten

print(a.reshape(2, 6))

print(a.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [27]:
print(a.reshape(3, -1)) # 3행만 지정해주고 열에 -1을 넣으면 자동으로 배열을 reshape한다.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 넘파이 브로드캐스팅

In [35]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,0,1])
y = np.empty_like(a) # 배열 a와 크기가 같은 원소가 비어있는 배열 생성

# 배열 b를 a의 각 행에 더해주기 위해 반복문을 사용한다.
for i in range(3):
    y[i, :] = a[i, :] + b
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [36]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,0,1])
c = a + b
print(c)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
