# 문장 백터화 진행

In [1]:
import numpy as np

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니 다.") 
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent) # 문장 벡터화 진행

idf = tfidf_vectorizer.idf_
print(dict(zip(tfidf_vectorizer.get_feature_names(), idf)))

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니': 1.4054651081081644, '있습니다': 1.4054651081081644, '중심': 1.4054651081081644, '폭염': 1.0, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일': 1.0}


In [9]:
list(zip(tfidf_vectorizer.get_feature_names(), idf))

[('갑작스런', 1.4054651081081644),
 ('내일', 1.4054651081081644),
 ('놀러왔다가', 1.4054651081081644),
 ('망연자실', 1.4054651081081644),
 ('반가운', 1.4054651081081644),
 ('서쪽', 1.4054651081081644),
 ('소식', 1.4054651081081644),
 ('오늘', 1.4054651081081644),
 ('으로', 1.4054651081081644),
 ('이어졌는데요', 1.4054651081081644),
 ('인해', 1.4054651081081644),
 ('있습니', 1.4054651081081644),
 ('있습니다', 1.4054651081081644),
 ('중심', 1.4054651081081644),
 ('폭염', 1.0),
 ('피해서', 1.4054651081081644),
 ('하고', 1.4054651081081644),
 ('휴일', 1.0)]

In [13]:
tfidf_vectorizer.vocabulary_

{'휴일': 17,
 '오늘': 7,
 '서쪽': 5,
 '중심': 13,
 '으로': 8,
 '폭염': 14,
 '이어졌는데요': 9,
 '내일': 1,
 '반가운': 4,
 '소식': 6,
 '있습니다': 12,
 '피해서': 15,
 '놀러왔다가': 2,
 '갑작스런': 0,
 '인해': 10,
 '망연자실': 3,
 '하고': 16,
 '있습니': 11}

# 유사도의 예
 1. 자카드 유사도
 2. 코사인 유사도
 3. 유클리디안 유사도
 4. 멘하탄 유사도

In [21]:
# 1. 자카드 유사도 : 벡터화 없이 유사도 측정이 가능
# 교집합/합집합
from sklearn.metrics import jaccard_score
jaccard_score(np.array([1,1,0,0]), np.array([1,1,0,2]), average=None)

array([0.5, 1. , 0. ])

In [23]:
# 2. 코사인 유사도

from sklearn.metrics.pairwise import cosine_similarity

# 코사인 유사도를 구해보자
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[0.11304078]])

In [26]:
# 3. 유클리디안 유사도 (L2-distance)

from sklearn.metrics.pairwise import euclidean_distances

print(euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2]))

# 정규화

import numpy as np

def l1_normalize(v):
    norm = np.sum(v)
    return v / norm

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

[[1.33188529]]


array([[0.21243357]])

In [25]:
# 4. 맨하탄 유사도 (L1-distance)

from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.85654185]])